name: Docker Remote (AWS) Cache 

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-central-1
  ECR_REPO_NAME: test-repository
  ENV_VAR: test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and use a new builder instance
        run: docker buildx create --name mybuilder --use

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          context: .
          push: true
          builder: mybuilder
          build-args: |
            - ENV_VAR=${{ env.ENV_VAR }}
          tags: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          cache-from: type=registry,ref=${ECR_REGISTRY}/${ECR_REPOSITORY}:cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${ECR_REGISTRY}/${ECR_REPOSITORY}:cache
